all:
	@cd can_activate && make --no-print-directory
	@cd current_keyboard && make --no-print-directory
	@cd decryptvault && make --no-print-directory
	@cd sudop && make --no-print-directory
	@cd update && make --no-print-directory
	@cd xdp-nuke && make --no-print-directory
