#!/home/avalon/miniconda3/bin/python3
import subprocess
import json

cmd = "hyprctl devices -j"

result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

if result.returncode != 0:
    print(result.stderr)
else:
    result = json.loads(result.stdout)
    keyboards = result["keyboards"]

    for keyboard in keyboards:
        if keyboard["main"]:
            print(keyboard["active_keymap"])
