# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'IngoMeyer441/tmux-easy-motion'
# set -g @plugin 'schasse/tmux-jump'

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g @jump-key 'f'

# undercurls
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -gq allow-passthrough on
set -g visual-activity off
set -g mouse on

set -sg escape-time 50
# Start at 1
set -g base-index 1
set -g pane-base-index 1

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind "v" copy-mode
# new window in cwd
bind "c" new-window -c "#{pane_current_path}"
bind "C" new-window
# Split in cwd
bind '"' split-window -v -c "#{pane_current_path}" -l 30%
bind "'" split-window -v -c "#{pane_current_path}" -l 30%
bind "È" split-window -v -c "#{pane_current_path}" -l 30%
bind % split-window -h -c "#{pane_current_path}"
# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

run '~/.tmux/plugins/tpm/tpm'
set-option -g status-position top
set -g status-right ""
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'


# INFO: Fixing the missing icon
window_number="#($HOME/.config/tmux/custom-number.sh #I -d)"

#+--- Windows ---+
# Focus
set -g window-status-current-format "#[fg=#44dfaf,bg=#1F2335]   #[fg=#a9b1d6]$window_number #[bold,nodim]#W#[nobold,dim]#{?window_zoomed_flag, $zoom_number, $custom_pane} #{?window_last_flag,,} "
# Unfocused
set -g window-status-format "#[fg=#c0caf5,bg=default,none,dim]   $window_number #W#[nobold,dim]#{?window_zoomed_flag, $zoom_number, $custom_pane}#[fg=yellow,blink] #{?window_last_flag,󰁯 ,} "
