# ------------------------------------------------------------
# LuaRocks
# ------------------------------------------------------------
[rocks]
luafilesystem = "1.8.0"
[config]
plugins_dir = "configs/"
# ------------------------------------------------------------
# Core plugins
# ------------------------------------------------------------
[plugins]
"rocks.nvim" = "2.27.1"
"rocks-config.nvim" = "1.6.0"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim" = { git = "nvim-lua/plenary.nvim", rev = "v0.1.4" }
# ------------------------------------------------------------
# Mason
# ------------------------------------------------------------
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
"mason-nvim-dap.nvim" = "2.2.2"
"mason-tool-installer.nvim" = { git = "WhoIsSethDaniel/mason-tool-installer.nvim" }
"oil.nvim" = "2.9.0"
tree-sitter-lua = "scm"
[bundles.mason]
items = [
  "mason.nvim",
  "mason-lspconfig.nvim",
  "mason-nvim-dap.nvim",
  "mason-tool-installer.nvim",
]
# ------------------------------------------------------------
# UI plugins
# ------------------------------------------------------------
[plugins."dressing.nvim"]
git = "stevearc/dressing.nvim"
rev = "v2.2.1"
[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
branch = "master"
[plugins.nvim-web-devicons]
git = "nvim-tree/nvim-web-devicons"
branch = "master"
config = "icons/init"
[plugins.nvim-navic]
git = "SmiteshP/nvim-navic"
[plugins."barbecue.nvim"]
git = "utilyre/barbecue.nvim"
rev = "v1.2.0"
[plugins."nui.nvim"]
git = "MunifTanjim/nui.nvim"
rev = "0.3.0"
[plugins.nvim-notify]
git = "rcarriga/nvim-notify"
branch = "master"
config = { render = "compact", background_colour = "Normal", stage = "slide" }
[plugins."noice.nvim"]
git = "folke/noice.nvim"
rev = "v3.0.1"
[plugins."neoscroll.nvim"]
git = "karb94/neoscroll.nvim"
branch = "master"
config = { stop_eof = false }
# ------------------------------------------------------------
# Colorscheme
# ------------------------------------------------------------
[plugins."tokyonight.nvim"]
version = "3.0.1"
[plugins."transparent.nvim"]
git = "xiyaowong/transparent.nvim"
[bundles.colorscheme]
items = ["tokyonight.nvim", "transparent.nvim"]
# ------------------------------------------------------------
# Editor plugins
# ------------------------------------------------------------
[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"
[plugins."mini.move"]
git = "echasnovski/mini.move"
rev = "v0.9.0^{}"
config = "configs/mini_move"
[plugins."ultimate-autopair.nvim"]
git = "altermo/ultimate-autopair.nvim"
[plugins.nvim-surround]
git = "kylechui/nvim-surround"
rev = "v2.1.8"
[plugins."mini.surround"]
git = "echasnovski/mini.surround"
rev = "v0.9.0^{}"
[bundles.surround]
items = ["nvim-surround", "mini.surround"]
[plugins."hop.nvim"]
git = "smoka7/hop.nvim"
rev = "v2.6.0"
[plugins.nvim-lint]
git = "mfussenegger/nvim-lint"
config = "configs/linting"
[plugins."formatter.nvim"]
git = "mhartington/formatter.nvim"
config = "configs/formatting"

# ------------------------------------------------------------
# Lsp plugins
# ------------------------------------------------------------
[plugins."nvim-lspconfig"]
version = "0.1.7"
[plugins."neoconf.nvim"]
version = "1.2.2"
[plugins."schemastore"]
git = "b0o/schemastore.nvim"
[plugins."neodev.nvim"]
git = "folke/neodev.nvim"
rev = "v2.5.2"
config = {}
[bundles.nvim-lsp]
items = ["nvim-lspconfig", "neoconf.nvim"]
# ------------------------------------------------------------
# Telescope plugins
# ------------------------------------------------------------
[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
tag = '0.1.6'
[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
[bundles.telescope]
items = ["telescope.nvim", "telescope-fzf-native.nvim"]
# ------------------------------------------------------------
# Git plugins
# ------------------------------------------------------------
[plugins."diffview.nvim"]
git = "sindrets/diffview.nvim"
config = {}
[plugins.neogit]
git = "NeogitOrg/neogit"
branch = "master"
# ------------------------------------------------------------
# Utility plugins
# ------------------------------------------------------------
[plugins."which-key.nvim"]
git = "folke/which-key.nvim"
config = "configs/whichkey"
[plugins.vim-tmux-navigator]
git = "christoomey/vim-tmux-navigator"
rev = "v1.0^{}"
[plugins."smart-splits.nvim"]
git = "mrjones2014/smart-splits.nvim"
rev = "v1.4.0"
config = "configs/splits"
