return {
	-- popup_input = {
	-- 	submit = "<M-Enter>",
	-- 	-- border
	-- },
	-- chat = {
	-- 	keymaps = {
	-- 		close = "<Cq>",
	-- 		toggle_settings = "<M-S>",
	-- 		toggle_sessions = "<M-s>",
	-- 		toggle_diff = "<M-d>",
	-- 	},
	-- },
	-- edit_with_instructions = {
	-- 	diff = true,
	-- 	keymaps = {
	-- 		accept = "<M-a>",
	-- 		close = "q",
	-- 		toggle_settings = "<M-s>",
	-- 		toggle_diff = "<M-d>",
	-- 	},
	-- },
}
